### ISSUE TITLE
About details of model training

### ISSUE THREAD

**Issue by Alive59** [nihalsid/mesh-gpt#2]
Thanks for introducing such a brilliant model. Before reading the code, I'm just curious about how many training data should be prepared if I wanna train a customized model? Since you mentioned in the paper that you trained the released model on a large mesh dataset but without detailed information.

**Comment by nihalsid** [comment]
Hi, Thank you so much for your interest! :)

In the paper, in the experiment section as well as the appendix we give extensive details about the dataset used and the preoprocessing applied.
